# Generated by Django 4.2.4 on 2023-09-24 19:04

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Item name')),
                ('photo', models.CharField(max_length=200, verbose_name='Item photo file_id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('description', models.TextField(max_length=3000, null=True, verbose_name='Description')),
                ('category_code', models.CharField(max_length=20, verbose_name='Category Code')),
                ('category_name', models.CharField(max_length=20, verbose_name='Category Name')),
                ('subcategory_code', models.CharField(max_length=20, verbose_name='Subcategory Code')),
                ('subcategory_name', models.CharField(max_length=20, verbose_name='Subcategory Name')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(default=1, unique=True, verbose_name='Telegram user id')),
                ('name', models.CharField(max_length=100, verbose_name='Telegram user actual name')),
                ('username', models.CharField(max_length=100, verbose_name='Telegram user username')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('referrer_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('purchase_time', models.DateTimeField(auto_now_add=True, verbose_name='Purchase Time')),
                ('shipping_address', jsonfield.fields.JSONField(null=True, verbose_name='Shipping Address')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email Address')),
                ('receiver', models.CharField(max_length=100, null=True, verbose_name='Receiver Name')),
                ('successful', models.BooleanField(default=False, verbose_name='Successfull payment')),
                ('buyer', models.ForeignKey(on_delete=models.SET(0), to='accounts.user', verbose_name='Buyer')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.item', verbose_name='Item ID')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
    ]
